In [2]:
import pandas as pd
from io import StringIO

# read text file and only keep trip records
with open("trips.txt", "r", encoding="cp1252", errors="replace") as f:
    t_lines = [line for line in f if line.startswith("T;")]

# parse the trip records as pandas df
df_trips = pd.read_csv(StringIO("".join(t_lines)), sep=";", header=None, engine="python")

# select only columns with useful information
df_trips = df_trips.iloc[:, [0,1,2,5,6,7,8,-3]]

df_trips.columns = [
    "record_type",
    "line_number",
    "trip_number",
    # "trip_direction",
    # "variant_code",
    "from_stop",
    "start_time_min",
    "end_time_min",
    "to_stop",
    "distance_km"
]

df_trips["distance_km"] = pd.to_numeric(df_trips["distance_km"], errors="coerce")
df_trips.head()

,record_type,line_number,trip_number,from_stop,start_time_min,end_time_min,to_stop,distance_km
0,T,u001,1001,utrvec,350,389,utrijs,12.983
1,T,u001,1003,utrvec,364,404,utrijs,12.983
2,T,u001,1005,utrvec,377,419,utrijs,12.983
3,T,u001,1007,utrvec,389,434,utrijs,12.983
4,T,u001,1009,utrvec,403,449,utrijs,12.983

In [3]:
# read text file and only keep deadhead records

with open("dhd.txt", "r", encoding="cp1252", errors="replace") as f:
    t_lines = [line for line in f if line.startswith("D;")]

# parse the deadhead records as pandas df
df_deadheads = pd.read_csv(StringIO("".join(t_lines)), sep=";", header=None, engine="python")

# select only columns with useful information
df_deadheads = df_deadheads.iloc[:, [0,1,2,3,4,5,6]]

df_deadheads.columns = [
    "record_type",
    "from_stop-to_stop",
    "time_ver_0",
    "time_ver_1",
    "time_ver_2",
    "time_ver_3",
    "distance_km",
]
df_deadheads["distance_km"] = pd.to_numeric(df_deadheads["distance_km"], errors="coerce")
df_deadheads[["from_stop", "to_stop"]] = df_deadheads["from_stop-to_stop"].str.split("-", n=1, expand=True)
df_deadheads.head()

,record_type,from_stop-to_stop,time_ver_0,time_ver_1,time_ver_2,time_ver_3,distance_km,from_stop,to_stop
0,D,amdjwp-nwggam,26,26,26,26,20.0,amdjwp,nwggam
1,D,amdpri-nwggam,27,27,27,27,20.9,amdpri,nwggam
2,D,amdpri-sllgar,25,34,25,25,19.0,amdpri,sllgar
3,D,amdpri-utrgar,40,60,40,40,28.0,amdpri,utrgar
4,D,amdpri-wbdgar,55,65,55,55,43.0,amdpri,wbdgar

In [4]:
with open("parameters.txt", "r", encoding="cp1252", errors="replace") as f:
    t_lines = [line for line in f if line.startswith("U;")]

# read text file and only keep parameters records
df_params = pd.read_csv(StringIO("".join(t_lines)), sep=";", header=None, engine="python")

# parse the parameters records as pandas df
df_params = df_params.iloc[:, [0,2,4,9,10,12]]

# select only columns with useful information
df_params.columns = [
    "record_type",
    "cost_per_bus",
    # "cost_per_minute",
    "cost_per_km",
    "energy_compsumtion_kwh/km",
    "max_charge_rate_kwh/min",
    "battery_capacity_kwh"
]

df_params.head()

,record_type,cost_per_bus,cost_per_km,energy_compsumtion_kwh/km,max_charge_rate_kwh/min,battery_capacity_kwh
0,U,244.13,0.13,1.3,2.5,199.04

In [26]:
def build_deadhead_dict(df_deadheads):
    dh_dict = {}

    for row in df_deadheads.itertuples():
        dh_dict[(row.from_stop, row.to_stop)] = (
            row.time_ver_0,
            row.time_ver_1,
            row.time_ver_2,
            row.time_ver_3
        )

    return dh_dict

def feasible_arcs(trips, deadhead_dict, max_wait = 240):
    arcs = []
    trips_list = list(df_trips.itertuples())

    for i in trips_list:
        for j in trips_list:
            if i.trip_number == j.trip_number:
                continue
            
            if i.to_stop == j.from_stop:
                travel_time = 0
            else:
                key = (i.to_stop, j.from_stop)
                
                if key not in deadhead_dict:
                    continue

                t0, t1, t2, t3 = deadhead_dict[key]
                
                # check in which interval deadhead falls
                if  331 <= i.end_time_mine <= 419 or 541 <= i.end_time_min <= 899 or 1141 <= i.end_time_min <= 1439 or 1771 <= i.end_time_min <= 1859 or 1981 <= i.end_time_min <= 1999:
                    travel_time = t0
                elif 420 <= i.end_time_mine <= 540 or 900 <= i.end_time_min <= 1140 or 1860 <= i.end_time_min <= 1980:
                    travel_time = t1
                elif 0 <= i.end_time_mine <= 330 or 1440 <= i.end_time_min <= 1770:
                    travel_time = t2
                else:
                    travel_time = t3

            slack = j.start_time_min - (i.end_time_min + travel_time)

            if 0 <= slack <= max_wait:
                arcs.append((i.trip_number, j.trip_number, travel_time, slack))

    return arcs

deadhead_dict = build_deadhead_dict(df_deadheads)
        
feasible_arcs(df_trips, deadhead_dict)

[(1001, 1006, 0, 1),
 (1001, 1008, 0, 16),
 (1001, 1010, 0, 31),
 (1001, 1012, 0, 41),
 (1001, 1014, 0, 51),
 (1001, 1016, 0, 61),
 (1001, 1018, 0, 71),
 (1001, 1020, 0, 81),
 (1001, 1022, 0, 91),
 (1001, 1024, 0, 101),
 (1001, 1026, 0, 111),
 (1001, 1028, 0, 121),
 (1001, 1030, 0, 131),
 (1001, 1032, 0, 141),
 (1001, 1034, 0, 151),
 (1001, 1036, 0, 161),
 (1001, 1038, 0, 171),
 (1001, 1040, 0, 181),
 (1001, 1042, 0, 191),
 (1001, 1044, 0, 201),
 (1001, 1046, 0, 211),
 (1001, 1048, 0, 221),
 (1001, 1050, 0, 231),
 (1003, 1008, 0, 1),
 (1003, 1010, 0, 16),
 (1003, 1012, 0, 26),
 (1003, 1014, 0, 36),
 (1003, 1016, 0, 46),
 (1003, 1018, 0, 56),
 (1003, 1020, 0, 66),
 (1003, 1022, 0, 76),
 (1003, 1024, 0, 86),
 (1003, 1026, 0, 96),
 (1003, 1028, 0, 106),
 (1003, 1030, 0, 116),
 (1003, 1032, 0, 126),
 (1003, 1034, 0, 136),
 (1003, 1036, 0, 146),
 (1003, 1038, 0, 156),
 (1003, 1040, 0, 166),
 (1003, 1042, 0, 176),
 (1003, 1044, 0, 186),
 (1003, 1046, 0, 196),
 (1003, 1048, 0, 206),
 (1003, 1050, 0, 216),
 (1003, 1052, 0, 226),
 (1003, 1054, 0, 236),
 (1005, 1010, 0, 1),
 (1005, 1012, 0, 11),
 (1005, 1014, 0, 21),
 (1005, 1016, 0, 31),
 (1005, 1018, 0, 41),
 (1005, 1020, 0, 51),
 (1005, 1022, 0, 61),
 (1005, 1024, 0, 71),
 (1005, 1026, 0, 81),
 (1005, 1028, 0, 91),
 (1005, 1030, 0, 101),
 (1005, 1032, 0, 111),
 (1005, 1034, 0, 121),
 (1005, 1036, 0, 131),
 (1005, 1038, 0, 141),
 (1005, 1040, 0, 151),
 (1005, 1042, 0, 161),
 (1005, 1044, 0, 171),
 (1005, 1046, 0, 181),
 (1005, 1048, 0, 191),
 (1005, 1050, 0, 201),
 (1005, 1052, 0, 211),
 (1005, 1054, 0, 221),
 (1005, 1056, 0, 231),
 (1007, 1014, 0, 6),
 (1007, 1016, 0, 16),
 (1007, 1018, 0, 26),
 (1007, 1020, 0, 36),
 (1007, 1022, 0, 46),
 (1007, 1024, 0, 56),
 (1007, 1026, 0, 66),
 (1007, 1028, 0, 76),
 (1007, 1030, 0, 86),
 (1007, 1032, 0, 96),
 (1007, 1034, 0, 106),
 (1007, 1036, 0, 116),
 (1007, 1038, 0, 126),
 (1007, 1040, 0, 136),
 (1007, 1042, 0, 146),
 (1007, 1044, 0, 156),
 (1007, 1046, 0, 166),
 (1007, 1048, 0, 176),
 (1007, 1050, 0, 186),
 (1007, 1052, 0, 196),
 (1007, 1054, 0, 206),
 (1007, 1056, 0, 216),
 (1007, 1058, 0, 226),
 (1007, 1060, 0, 236),
 (1009, 1016, 0, 1),
 (1009, 1018, 0, 11),
 (1009, 1020, 0, 21),
 (1009, 1022, 0, 31),
 (1009, 1024, 0, 41),
 (1009, 1026, 0, 51),
 (1009, 1028, 0, 61),
 (1009, 1030, 0, 71),
 (1009, 1032, 0, 81),
 (1009, 1034, 0, 91),
 (1009, 1036, 0, 101),
 (1009, 1038, 0, 111),
 (1009, 1040, 0, 121),
 (1009, 1042, 0, 131),
 (1009, 1044, 0, 141),
 (1009, 1046, 0, 151),
 (1009, 1048, 0, 161),
 (1009, 1050, 0, 171),
 (1009, 1052, 0, 181),
 (1009, 1054, 0, 191),
 (1009, 1056, 0, 201),
 (1009, 1058, 0, 211),
 (1009, 1060, 0, 221),
 (1009, 1062, 0, 231),
 (1011, 1018, 0, 1),
 (1011, 1020, 0, 11),
 (1011, 1022, 0, 21),
 (1011, 1024, 0, 31),
 (1011, 1026, 0, 41),
 (1011, 1028, 0, 51),
 (1011, 1030, 0, 61),
 (1011, 1032, 0, 71),
 (1011, 1034, 0, 81),
 (1011, 1036, 0, 91),
 (1011, 1038, 0, 101),
 (1011, 1040, 0, 111),
 (1011, 1042, 0, 121),
 (1011, 1044, 0, 131),
 (1011, 1046, 0, 141),
 (1011, 1048, 0, 151),
 (1011, 1050, 0, 161),
 (1011, 1052, 0, 171),
 (1011, 1054, 0, 181),
 (1011, 1056, 0, 191),
 (1011, 1058, 0, 201),
 (1011, 1060, 0, 211),
 (1011, 1062, 0, 221),
 (1011, 1064, 0, 231),
 (1013, 1020, 0, 1),
 (1013, 1022, 0, 11),
 (1013, 1024, 0, 21),
 (1013, 1026, 0, 31),
 (1013, 1028, 0, 41),
 (1013, 1030, 0, 51),
 (1013, 1032, 0, 61),
 (1013, 1034, 0, 71),
 (1013, 1036, 0, 81),
 (1013, 1038, 0, 91),
 (1013, 1040, 0, 101),
 (1013, 1042, 0, 111),
 (1013, 1044, 0, 121),
 (1013, 1046, 0, 131),
 (1013, 1048, 0, 141),
 (1013, 1050, 0, 151),
 (1013, 1052, 0, 161),
 (1013, 1054, 0, 171),
 (1013, 1056, 0, 181),
 (1013, 1058, 0, 191),
 (1013, 1060, 0, 201),
 (1013, 1062, 0, 211),
 (1013, 1064, 0, 221),
 (1013, 1066, 0, 231),
 (1015, 1022, 0, 1),
 (1015, 1024, 0, 11),
 (1015, 1026, 0, 21),
 (1015, 1028, 0, 31),
 (1015, 1030, 0, 41),
 (1015, 1032, 0, 51),
 (1015, 1034, 0, 61),
 (1015, 1036, 0, 71),
 (1015, 1038, 0, 81),
 (1015, 1040, 0, 91),
 (1015, 1042, 0, 101),
 (1015, 1044, 0, 111),
 (1015, 1046, 0, 121),
 (1015, 1048, 0, 131),
 (1015, 1050, 0, 141),
 (1015, 1052, 0, 151),
 (1015, 1054, 0, 161),
 (1015, 1056, 0, 171),
 (1015, 1058, 0, 181),
 (1015, 1060, 0, 191),
 (1015, 1062, 0, 201),
 (1015, 1064, 0, 211),
 (1015, 1066, 0, 221),
 (1015, 1068, 0, 231),
 (1017, 1024, 0, 1),
 (1017, 1026, 0, 11),
 (1017, 1028, 0, 21),
 (1017, 1030, 0, 31),
 (1017, 1032, 0, 41),
 (1017, 1034, 0, 51),
 (1017, 1036, 0, 61),
 (1017, 1038, 0, 71),
 (1017, 1040, 0, 81),
 (1017, 1042, 0, 91),
 (1017, 1044, 0, 101),
 (1017, 1046, 0, 111),
 (1017, 1048, 0, 121),
 (1017, 1050, 0, 131),
 (1017, 1052, 0, 141),
 (1017, 1054, 0, 151),
 (1017, 1056, 0, 161),
 (1017, 1058, 0, 171),
 (1017, 1060, 0, 181),
 (1017, 1062, 0, 191),
 (1017, 1064, 0, 201),
 (1017, 1066, 0, 211),
 (1017, 1068, 0, 221),
 (1017, 1070, 0, 231),
 (1019, 1026, 0, 1),
 (1019, 1028, 0, 11),
 (1019, 1030, 0, 21),
 (1019, 1032, 0, 31),
 (1019, 1034, 0, 41),
 (1019, 1036, 0, 51),
 (1019, 1038, 0, 61),
 (1019, 1040, 0, 71),
 (1019, 1042, 0, 81),
 (1019, 1044, 0, 91),
 (1019, 1046, 0, 101),
 (1019, 1048, 0, 111),
 (1019, 1050, 0, 121),
 (1019, 1052, 0, 131),
 (1019, 1054, 0, 141),
 (1019, 1056, 0, 151),
 (1019, 1058, 0, 161),
 (1019, 1060, 0, 171),
 (1019, 1062, 0, 181),
 (1019, 1064, 0, 191),
 (1019, 1066, 0, 201),
 (1019, 1068, 0, 211),
 (1019, 1070, 0, 221),
 (1019, 1072, 0, 231),
 (1021, 1028, 0, 1),
 (1021, 1030, 0, 11),
 (1021, 1032, 0, 21),
 (1021, 1034, 0, 31),
 (1021, 1036, 0, 41),
 (1021, 1038, 0, 51),
 (1021, 1040, 0, 61),
 (1021, 1042, 0, 71),
 (1021, 1044, 0, 81),
 (1021, 1046, 0, 91),
 (1021, 1048, 0, 101),
 (1021, 1050, 0, 111),
 (1021, 1052, 0, 121),
 (1021, 1054, 0, 131),
 (1021, 1056, 0, 141),
 (1021, 1058, 0, 151),
 (1021, 1060, 0, 161),
 (1021, 1062, 0, 171),
 (1021, 1064, 0, 181),
 (1021, 1066, 0, 191),
 (1021, 1068, 0, 201),
 (1021, 1070, 0, 211),
 (1021, 1072, 0, 221),
 (1021, 1074, 0, 231),
 (1023, 1030, 0, 1),
 (1023, 1032, 0, 11),
 (1023, 1034, 0, 21),
 (1023, 1036, 0, 31),
 (1023, 1038, 0, 41),
 (1023, 1040, 0, 51),
 (1023, 1042, 0, 61),
 (1023, 1044, 0, 71),
 (1023, 1046, 0, 81),
 (1023, 1048, 0, 91),
 (1023, 1050, 0, 101),
 (1023, 1052, 0, 111),
 (1023, 1054, 0, 121),
 (1023, 1056, 0, 131),
 (1023, 1058, 0, 141),
 (1023, 1060, 0, 151),
 (1023, 1062, 0, 161),
 (1023, 1064, 0, 171),
 (1023, 1066, 0, 181),
 (1023, 1068, 0, 191),
 (1023, 1070, 0, 201),
 (1023, 1072, 0, 211),
 (1023, 1074, 0, 221),
 (1023, 1076, 0, 231),
 (1025, 1032, 0, 1),
 (1025, 1034, 0, 11),
 (1025, 1036, 0, 21),
 (1025, 1038, 0, 31),
 (1025, 1040, 0, 41),
 (1025, 1042, 0, 51),
 (1025, 1044, 0, 61),
 (1025, 1046, 0, 71),
 (1025, 1048, 0, 81),
 (1025, 1050, 0, 91),
 (1025, 1052, 0, 101),
 (1025, 1054, 0, 111),
 (1025, 1056, 0, 121),
 (1025, 1058, 0, 131),
 (1025, 1060, 0, 141),
 (1025, 1062, 0, 151),
 (1025, 1064, 0, 161),
 (1025, 1066, 0, 171),
 (1025, 1068, 0, 181),
 (1025, 1070, 0, 191),
 (1025, 1072, 0, 201),
 (1025, 1074, 0, 211),
 (1025, 1076, 0, 221),
 (1025, 1078, 0, 231),
 (1027, 1034, 0, 1),
 (1027, 1036, 0, 11),
 (1027, 1038, 0, 21),
 (1027, 1040, 0, 31),
 (1027, 1042, 0, 41),
 (1027, 1044, 0, 51),
 (1027, 1046, 0, 61),
 (1027, 1048, 0, 71),
 (1027, 1050, 0, 81),
 (1027, 1052, 0, 91),
 (1027, 1054, 0, 101),
 (1027, 1056, 0, 111),
 (1027, 1058, 0, 121),
 (1027, 1060, 0, 131),
 (1027, 1062, 0, 141),
 (1027, 1064, 0, 151),
 (1027, 1066, 0, 161),
 (1027, 1068, 0, 171),
 (1027, 1070, 0, 181),
 (1027, 1072, 0, 191),
 (1027, 1074, 0, 201),
 (1027, 1076, 0, 211),
 (1027, 1078, 0, 221),
 (1027, 1080, 0, 231),
 (1029, 1036, 0, 1),
 (1029, 1038, 0, 11),
 (1029, 1040, 0, 21),
 (1029, 1042, 0, 31),
 (1029, 1044, 0, 41),
 (1029, 1046, 0, 51),
 (1029, 1048, 0, 61),
 (1029, 1050, 0, 71),
 (1029, 1052, 0, 81),
 (1029, 1054, 0, 91),
 (1029, 1056, 0, 101),
 (1029, 1058, 0, 111),
 (1029, 1060, 0, 121),
 (1029, 1062, 0, 131),
 (1029, 1064, 0, 141),
 (1029, 1066, 0, 151),
 (1029, 1068, 0, 161),
 (1029, 1070, 0, 171),
 (1029, 1072, 0, 181),
 (1029, 1074, 0, 191),
 (1029, 1076, 0, 201),
 (1029, 1078, 0, 211),
 (1029, 1080, 0, 221),
 (1029, 1082, 0, 231),
 (1031, 1038, 0, 1),
 (1031, 1040, 0, 11),
 (1031, 1042, 0, 21),
 (1031, 1044, 0, 31),
 (1031, 1046, 0, 41),
 (1031, 1048, 0, 51),
 (1031, 1050, 0, 61),
 (1031, 1052, 0, 71),
 (1031, 1054, 0, 81),
 (1031, 1056, 0, 91),
 (1031, 1058, 0, 101),
 (1031, 1060, 0, 111),
 (1031, 1062, 0, 121),
 (1031, 1064, 0, 131),
 (1031, 1066, 0, 141),
 (1031, 1068, 0, 151),
 (1031, 1070, 0, 161),
 (1031, 1072, 0, 171),
 (1031, 1074, 0, 181),
 (1031, 1076, 0, 191),
 (1031, 1078, 0, 201),
 (1031, 1080, 0, 211),
 (1031, 1082, 0, 221),
 (1031, 1084, 0, 231),
 (1033, 1040, 0, 1),
 (1033, 1042, 0, 11),
 (1033, 1044, 0, 21),
 (1033, 1046, 0, 31),
 (1033, 1048, 0, 41),
 (1033, 1050, 0, 51),
 (1033, 1052, 0, 61),
 (1033, 1054, 0, 71),
 (1033, 1056, 0, 81),
 (1033, 1058, 0, 91),
 (1033, 1060, 0, 101),
 (1033, 1062, 0, 111),
 (1033, 1064, 0, 121),
 (1033, 1066, 0, 131),
 (1033, 1068, 0, 141),
 (1033, 1070, 0, 151),
 (1033, 1072, 0, 161),
 (1033, 1074, 0, 171),
 (1033, 1076, 0, 181),
 (1033, 1078, 0, 191),
 (1033, 1080, 0, 201),
 (1033, 1082, 0, 211),
 (1033, 1084, 0, 221),
 (1033, 1086, 0, 231),
 (1035, 1042, 0, 1),
 (1035, 1044, 0, 11),
 (1035, 1046, 0, 21),
 (1035, 1048, 0, 31),
 (1035, 1050, 0, 41),
 (1035, 1052, 0, 51),
 (1035, 1054, 0, 61),
 (1035, 1056, 0, 71),
 (1035, 1058, 0, 81),
 (1035, 1060, 0, 91),
 (1035, 1062, 0, 101),
 (1035, 1064, 0, 111),
 (1035, 1066, 0, 121),
 (1035, 1068, 0, 131),
 (1035, 1070, 0, 141),
 (1035, 1072, 0, 151),
 (1035, 1074, 0, 161),
 (1035, 1076, 0, 171),
 (1035, 1078, 0, 181),
 (1035, 1080, 0, 191),
 (1035, 1082, 0, 201),
 (1035, 1084, 0, 211),
 (1035, 1086, 0, 221),
 (1035, 1088, 0, 231),
 (1037, 1044, 0, 1),
 (1037, 1046, 0, 11),
 (1037, 1048, 0, 21),
 (1037, 1050, 0, 31),
 (1037, 1052, 0, 41),
 (1037, 1054, 0, 51),
 (1037, 1056, 0, 61),
 (1037, 1058, 0, 71),
 (1037, 1060, 0, 81),
 (1037, 1062, 0, 91),
 (1037, 1064, 0, 101),
 (1037, 1066, 0, 111),
 (1037, 1068, 0, 121),
 (1037, 1070, 0, 131),
 (1037, 1072, 0, 141),
 (1037, 1074, 0, 151),
 (1037, 1076, 0, 161),
 (1037, 1078, 0, 171),
 (1037, 1080, 0, 181),
 (1037, 1082, 0, 191),
 (1037, 1084, 0, 201),
 (1037, 1086, 0, 211),
 (1037, 1088, 0, 221),
 (1037, 1090, 0, 231),
 (1039, 1046, 0, 1),
 (1039, 1048, 0, 11),
 (1039, 1050, 0, 21),
 (1039, 1052, 0, 31),
 (1039, 1054, 0, 41),
 (1039, 1056, 0, 51),
 (1039, 1058, 0, 61),
 (1039, 1060, 0, 71),
 (1039, 1062, 0, 81),
 (1039, 1064, 0, 91),
 (1039, 1066, 0, 101),
 (1039, 1068, 0, 111),
 (1039, 1070, 0, 121),
 (1039, 1072, 0, 131),
 (1039, 1074, 0, 141),
 (1039, 1076, 0, 151),
 (1039, 1078, 0, 161),
 (1039, 1080, 0, 171),
 (1039, 1082, 0, 181),
 (1039, 1084, 0, 191),
 (1039, 1086, 0, 201),
 (1039, 1088, 0, 211),
 (1039, 1090, 0, 221),
 (1039, 1092, 0, 231),
 (1041, 1048, 0, 1),
 (1041, 1050, 0, 11),
 (1041, 1052, 0, 21),
 (1041, 1054, 0, 31),
 (1041, 1056, 0, 41),
 (1041, 1058, 0, 51),
 (1041, 1060, 0, 61),
 (1041, 1062, 0, 71),
 (1041, 1064, 0, 81),
 (1041, 1066, 0, 91),
 (1041, 1068, 0, 101),
 (1041, 1070, 0, 111),
 (1041, 1072, 0, 121),
 (1041, 1074, 0, 131),
 (1041, 1076, 0, 141),
 (1041, 1078, 0, 151),
 (1041, 1080, 0, 161),
 (1041, 1082, 0, 171),
 (1041, 1084, 0, 181),
 (1041, 1086, 0, 191),
 (1041, 1088, 0, 201),
 (1041, 1090, 0, 211),
 (1041, 1092, 0, 221),
 (1041, 1094, 0, 231),
 (1043, 1050, 0, 1),
 (1043, 1052, 0, 11),
 (1043, 1054, 0, 21),
 (1043, 1056, 0, 31),
 (1043, 1058, 0, 41),
 (1043, 1060, 0, 51),
 (1043, 1062, 0, 61),
 (1043, 1064, 0, 71),
 (1043, 1066, 0, 81),
 (1043, 1068, 0, 91),
 (1043, 1070, 0, 101),
 (1043, 1072, 0, 111),
 (1043, 1074, 0, 121),
 (1043, 1076, 0, 131),
 (1043, 1078, 0, 141),
 (1043, 1080, 0, 151),
 (1043, 1082, 0, 161),
 (1043, 1084, 0, 171),
 (1043, 1086, 0, 181),
 (1043, 1088, 0, 191),
 (1043, 1090, 0, 201),
 (1043, 1092, 0, 211),
 (1043, 1094, 0, 221),
 (1043, 1096, 0, 231),
 (1045, 1052, 0, 1),
 (1045, 1054, 0, 11),
 (1045, 1056, 0, 21),
 (1045, 1058, 0, 31),
 (1045, 1060, 0, 41),
 (1045, 1062, 0, 51),
 (1045, 1064, 0, 61),
 (1045, 1066, 0, 71),
 (1045, 1068, 0, 81),
 (1045, 1070, 0, 91),
 (1045, 1072, 0, 101),
 (1045, 1074, 0, 111),
 (1045, 1076, 0, 121),
 (1045, 1078, 0, 131),
 (1045, 1080, 0, 141),
 (1045, 1082, 0, 151),
 (1045, 1084, 0, 161),
 (1045, 1086, 0, 171),
 (1045, 1088, 0, 181),
 (1045, 1090, 0, 191),
 (1045, 1092, 0, 201),
 (1045, 1094, 0, 211),
 (1045, 1096, 0, 221),
 (1045, 1098, 0, 231),
 (1047, 1054, 0, 1),
 (1047, 1056, 0, 11),
 (1047, 1058, 0, 21),
 (1047, 1060, 0, 31),
 (1047, 1062, 0, 41),
 (1047, 1064, 0, 51),
 (1047, 1066, 0, 61),
 (1047, 1068, 0, 71),
 (1047, 1070, 0, 81),
 (1047, 1072, 0, 91),
 (1047, 1074, 0, 101),
 (1047, 1076, 0, 111),
 (1047, 1078, 0, 121),
 (1047, 1080, 0, 131),
 (1047, 1082, 0, 141),
 (1047, 1084, 0, 151),
 (1047, 1086, 0, 161),
 (1047, 1088, 0, 171),
 (1047, 1090, 0, 181),
 (1047, 1092, 0, 191),
 (1047, 1094, 0, 201),
 (1047, 1096, 0, 211),
 (1047, 1098, 0, 221),
 (1047, 1100, 0, 231),
 (1049, 1056, 0, 1),
 (1049, 1058, 0, 11),
 (1049, 1060, 0, 21),
 (1049, 1062, 0, 31),
 (1049, 1064, 0, 41),
 (1049, 1066, 0, 51),
 (1049, 1068, 0, 61),
 (1049, 1070, 0, 71),
 (1049, 1072, 0, 81),
 (1049, 1074, 0, 91),
 (1049, 1076, 0, 101),
 (1049, 1078, 0, 111),
 (1049, 1080, 0, 121),
 (1049, 1082, 0, 131),
 (1049, 1084, 0, 141),
 (1049, 1086, 0, 151),
 (1049, 1088, 0, 161),
 (1049, 1090, 0, 171),
 (1049, 1092, 0, 181),
 (1049, 1094, 0, 191),
 (1049, 1096, 0, 201),
 (1049, 1098, 0, 211),
 (1049, 1100, 0, 221),
 (1049, 1102, 0, 231),
 (1051, 1058, 0, 1),
 (1051, 1060, 0, 11),
 (1051, 1062, 0, 21),
 (1051, 1064, 0, 31),
 (1051, 1066, 0, 41),
 (1051, 1068, 0, 51),
 (1051, 1070, 0, 61),
 (1051, 1072, 0, 71),
 (1051, 1074, 0, 81),
 (1051, 1076, 0, 91),
 (1051, 1078, 0, 101),
 (1051, 1080, 0, 111),
 (1051, 1082, 0, 121),
 (1051, 1084, 0, 131),
 (1051, 1086, 0, 141),
 (1051, 1088, 0, 151),
 (1051, 1090, 0, 161),
 (1051, 1092, 0, 171),
 (1051, 1094, 0, 181),
 (1051, 1096, 0, 191),
 (1051, 1098, 0, 201),
 (1051, 1100, 0, 211),
 (1051, 1102, 0, 221),
 (1051, 1104, 0, 231),
 (1053, 1060, 0, 1),
 (1053, 1062, 0, 11),
 (1053, 1064, 0, 21),
 (1053, 1066, 0, 31),
 (1053, 1068, 0, 41),
 (1053, 1070, 0, 51),
 (1053, 1072, 0, 61),
 (1053, 1074, 0, 71),
 (1053, 1076, 0, 81),
 (1053, 1078, 0, 91),
 (1053, 1080, 0, 101),
 (1053, 1082, 0, 111),
 (1053, 1084, 0, 121),
 (1053, 1086, 0, 131),
 (1053, 1088, 0, 141),
 (1053, 1090, 0, 151),
 (1053, 1092, 0, 161),
 (1053, 1094, 0, 171),
 (1053, 1096, 0, 181),
 (1053, 1098, 0, 191),
 (1053, 1100, 0, 201),
 (1053, 1102, 0, 211),
 (1053, 1104, 0, 221),
 (1053, 1106, 0, 231),
 (1055, 1062, 0, 1),
 (1055, 1064, 0, 11),
 (1055, 1066, 0, 21),
 (1055, 1068, 0, 31),
 (1055, 1070, 0, 41),
 (1055, 1072, 0, 51),
 (1055, 1074, 0, 61),
 (1055, 1076, 0, 71),
 (1055, 1078, 0, 81),
 (1055, 1080, 0, 91),
 (1055, 1082, 0, 101),
 (1055, 1084, 0, 111),
 (1055, 1086, 0, 121),
 (1055, 1088, 0, 131),
 (1055, 1090, 0, 141),
 (1055, 1092, 0, 151),
 (1055, 1094, 0, 161),
 (1055, 1096, 0, 171),
 (1055, 1098, 0, 181),
 (1055, 1100, 0, 191),
 (1055, 1102, 0, 201),
 (1055, 1104, 0, 211),
 (1055, 1106, 0, 221),
 (1055, 1108, 0, 231),
 (1057, 1064, 0, 1),
 (1057, 1066, 0, 11),
 (1057, 1068, 0, 21),
 (1057, 1070, 0, 31),
 (1057, 1072, 0, 41),
 (1057, 1074, 0, 51),
 (1057, 1076, 0, 61),
 (1057, 1078, 0, 71),
 (1057, 1080, 0, 81),
 (1057, 1082, 0, 91),
 (1057, 1084, 0, 101),
 (1057, 1086, 0, 111),
 (1057, 1088, 0, 121),
 (1057, 1090, 0, 131),
 (1057, 1092, 0, 141),
 (1057, 1094, 0, 151),
 (1057, 1096, 0, 161),
 (1057, 1098, 0, 171),
 (1057, 1100, 0, 181),
 (1057, 1102, 0, 191),
 (1057, 1104, 0, 201),
 (1057, 1106, 0, 211),
 (1057, 1108, 0, 221),
 (1057, 1110, 0, 231),
 (1059, 1066, 0, 1),
 (1059, 1068, 0, 11),
 (1059, 1070, 0, 21),
 (1059, 1072, 0, 31),
 (1059, 1074, 0, 41),
 (1059, 1076, 0, 51),
 (1059, 1078, 0, 61),
 (1059, 1080, 0, 71),
 (1059, 1082, 0, 81),
 (1059, 1084, 0, 91),
 (1059, 1086, 0, 101),
 (1059, 1088, 0, 111),
 (1059, 1090, 0, 121),
 (1059, 1092, 0, 131),
 (1059, 1094, 0, 141),
 (1059, 1096, 0, 151),
 (1059, 1098, 0, 161),
 (1059, 1100, 0, 171),
 (1059, 1102, 0, 181),
 (1059, 1104, 0, 191),
 (1059, 1106, 0, 201),
 (1059, 1108, 0, 211),
 (1059, 1110, 0, 221),
 (1059, 1112, 0, 231),
 (1061, 1068, 0, 1),
 (1061, 1070, 0, 11),
 (1061, 1072, 0, 21),
 (1061, 1074, 0, 31),
 (1061, 1076, 0, 41),
 (1061, 1078, 0, 51),
 (1061, 1080, 0, 61),
 (1061, 1082, 0, 71),
 (1061, 1084, 0, 81),
 (1061, 1086, 0, 91),
 (1061, 1088, 0, 101),
 (1061, 1090, 0, 111),
 (1061, 1092, 0, 121),
 (1061, 1094, 0, 131),
 (1061, 1096, 0, 141),
 (1061, 1098, 0, 151),
 (1061, 1100, 0, 161),
 (1061, 1102, 0, 171),
 (1061, 1104, 0, 181),
 (1061, 1106, 0, 191),
 (1061, 1108, 0, 201),
 (1061, 1110, 0, 211),
 (1061, 1112, 0, 221),
 (1061, 1114, 0, 231),
 (1063, 1070, 0, 1),
 (1063, 1072, 0, 11),
 (1063, 1074, 0, 21),
 (1063, 1076, 0, 31),
 (1063, 1078, 0, 41),
 (1063, 1080, 0, 51),
 (1063, 1082, 0, 61),
 (1063, 1084, 0, 71),
 (1063, 1086, 0, 81),
 (1063, 1088, 0, 91),
 (1063, 1090, 0, 101),
 (1063, 1092, 0, 111),
 (1063, 1094, 0, 121),
 (1063, 1096, 0, 131),
 (1063, 1098, 0, 141),
 (1063, 1100, 0, 151),
 (1063, 1102, 0, 161),
 (1063, 1104, 0, 171),
 (1063, 1106, 0, 181),
 (1063, 1108, 0, 191),
 (1063, 1110, 0, 201),
 (1063, 1112, 0, 211),
 (1063, 1114, 0, 221),
 (1063, 1116, 0, 231),
 (1065, 1072, 0, 1),
 (1065, 1074, 0, 11),
 (1065, 1076, 0, 21),
 (1065, 1078, 0, 31),
 (1065, 1080, 0, 41),
 (1065, 1082, 0, 51),
 (1065, 1084, 0, 61),
 (1065, 1086, 0, 71),
 (1065, 1088, 0, 81),
 (1065, 1090, 0, 91),
 (1065, 1092, 0, 101),
 (1065, 1094, 0, 111),
 (1065, 1096, 0, 121),
 (1065, 1098, 0, 131),
 (1065, 1100, 0, 141),
 (1065, 1102, 0, 151),
 (1065, 1104, 0, 161),
 (1065, 1106, 0, 171),
 (1065, 1108, 0, 181),
 (1065, 1110, 0, 191),
 (1065, 1112, 0, 201),
 (1065, 1114, 0, 211),
 (1065, 1116, 0, 221),
 (1065, 1118, 0, 231),
 (1067, 1074, 0, 1),
 (1067, 1076, 0, 11),
 (1067, 1078, 0, 21),
 (1067, 1080, 0, 31),
 (1067, 1082, 0, 41),
 (1067, 1084, 0, 51),
 (1067, 1086, 0, 61),
 (1067, 1088, 0, 71),
 (1067, 1090, 0, 81),
 (1067, 1092, 0, 91),
 (1067, 1094, 0, 101),
 (1067, 1096, 0, 111),
 (1067, 1098, 0, 121),
 (1067, 1100, 0, 131),
 (1067, 1102, 0, 141),
 (1067, 1104, 0, 151),
 (1067, 1106, 0, 161),
 (1067, 1108, 0, 171),
 (1067, 1110, 0, 181),
 (1067, 1112, 0, 191),
 (1067, 1114, 0, 201),
 (1067, 1116, 0, 211),
 (1067, 1118, 0, 221),
 (1067, 1120, 0, 231),
 (1069, 1076, 0, 1),
 (1069, 1078, 0, 11),
 (1069, 1080, 0, 21),
 (1069, 1082, 0, 31),
 (1069, 1084, 0, 41),
 (1069, 1086, 0, 51),
 (1069, 1088, 0, 61),
 (1069, 1090, 0, 71),
 (1069, 1092, 0, 81),
 (1069, 1094, 0, 91),
 (1069, 1096, 0, 101),
 (1069, 1098, 0, 111),
 (1069, 1100, 0, 121),
 (1069, 1102, 0, 131),
 (1069, 1104, 0, 141),
 (1069, 1106, 0, 151),
 (1069, 1108, 0, 161),
 (1069, 1110, 0, 171),
 (1069, 1112, 0, 181),
 (1069, 1114, 0, 191),
 (1069, 1116, 0, 201),
 (1069, 1118, 0, 211),
 (1069, 1120, 0, 221),
 (1069, 1122, 0, 231),
 (1071, 1078, 0, 1),
 (1071, 1080, 0, 11),
 (1071, 1082, 0, 21),
 (1071, 1084, 0, 31),
 (1071, 1086, 0, 41),
 (1071, 1088, 0, 51),
 (1071, 1090, 0, 61),
 (1071, 1092, 0, 71),
 (1071, 1094, 0, 81),
 (1071, 1096, 0, 91),
 (1071, 1098, 0, 101),
 (1071, 1100, 0, 111),
 (1071, 1102, 0, 121),
 (1071, 1104, 0, 131),
 (1071, 1106, 0, 141),
 (1071, 1108, 0, 151),
 (1071, 1110, 0, 161),
 (1071, 1112, 0, 171),
 (1071, 1114, 0, 181),
 (1071, 1116, 0, 191),
 (1071, 1118, 0, 201),
 (1071, 1120, 0, 211),
 (1071, 1122, 0, 221),
 (1071, 1124, 0, 231),
 (1073, 1080, 0, 1),
 (1073, 1082, 0, 11),
 (1073, 1084, 0, 21),
 (1073, 1086, 0, 31),
 (1073, 1088, 0, 41),
 (1073, 1090, 0, 51),
 (1073, 1092, 0, 61),
 (1073, 1094, 0, 71),
 (1073, 1096, 0, 81),
 (1073, 1098, 0, 91),
 (1073, 1100, 0, 101),
 (1073, 1102, 0, 111),
 (1073, 1104, 0, 121),
 (1073, 1106, 0, 131),
 (1073, 1108, 0, 141),
 (1073, 1110, 0, 151),
 (1073, 1112, 0, 161),
 (1073, 1114, 0, 171),
 (1073, 1116, 0, 181),
 (1073, 1118, 0, 191),
 (1073, 1120, 0, 201),
 (1073, 1122, 0, 211),
 (1073, 1124, 0, 221),
 (1073, 1126, 0, 231),